# $Id: Makefile 8858 2014-02-07 04:26:55Z takuya-i $

top_builddir = ../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SCRIPTS = $(srcdir)/gfpcopy-stress

include $(top_srcdir)/makes/script.mk
