# $Id: Makefile 6185 2012-03-28 10:51:07Z yuichironaito $

top_builddir = ../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SCRIPTS = $(srcdir)/gfpcopy-test.sh

include $(top_srcdir)/makes/script.mk
